<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

     <xacro:include filename="$(find tricycle_description)/urdf/includes/materials.urdf.xacro"/>
	<xacro:property name="M_PI" value="3.1415926535897931" />

	<xacro:macro name="cylinder_inertial_with_origin" params="radius length mass *origin">
		<inertial>
			<mass value="${mass}" />
			<insert_block name="origin" />
			<inertia ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0"
			iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0"
			izz="${0.5 * mass * radius * radius}" />
		</inertial>
	</xacro:macro>

	<xacro:macro name="cylinder_inertial" params="radius length mass">
		<inertial>
			<mass value="${mass}" />
			<origin xyz="0 0 0" />
			<inertia ixx="${0.0833333 * mass * (3 * radius * radius + length * length)}" ixy="0.0" ixz="0.0"
			iyy="${0.0833333 * mass * (3 * radius * radius + length * length)}" iyz="0.0"
			izz="${0.5 * mass * radius * radius}" />
		</inertial>
	</xacro:macro>

	<xacro:macro name="box_inertial_with_origin" params="x y z mass origin">
		<inertial>
			<mass value="${mass}" />
			<origin xyz="${origin}" />
			<inertia ixx="${0.0833333 * mass * (y*y + z*z)}" ixy="0.0" ixz="0.0"
			iyy="${0.0833333 * mass * (x*x + z*z)}" iyz="0.0"
			izz="${0.0833333 * mass * (x*x + y*y)}" />
		</inertial>
	</xacro:macro>

	<xacro:macro name="box_inertial" params="x y z mass">
		<inertial>
			<mass value="${mass}" />
			<origin xyz="0 0 0" />
			<inertia ixx="${0.0833333 * mass * (y*y + z*z)}" ixy="0.0" ixz="0.0"
			iyy="${0.0833333 * mass * (x*x + z*z)}" iyz="0.0"
			izz="${0.0833333 * mass * (x*x + y*y)}" />
		</inertial>
	</xacro:macro>

     <!-- ====================================================
                           Chassis
     ========================================================= -->

	<xacro:macro name="tricycle_chassis" params="name parent dx dy dz xyz rpy color">
		<!-- Chassis -->
		<joint name="${parent}_${name}_joint" type="fixed">
			<origin xyz="${xyz}" rpy="${rpy}"/>
			<parent link="${parent}"/>
			<child link="${name}"/>
		</joint>

		<link name="${name}">
			<visual name="${name}_visual">
				<geometry name="${name}_geometry">
					<box size="${dx} ${dy} ${dz}"/>
				</geometry>
				<xacro:color_material color="${color}"/>
			</visual>
			<collision>
				<geometry>
					<box size="${dx} ${dy} ${dz}"/>
				</geometry>
			</collision>
			<xacro:box_inertial x="${dx}" y="${dy}"  z="${dz}" mass="10.0"/>
		</link>

		<xacro:color_gazebo parent="${name}" color="${color}"/>
	</xacro:macro>

	<!-- ====================================================
                           Wheel Links
     ========================================================= -->
	<xacro:macro name="tricycle_wheel" params="name parent xyz rpy radius length flip=1 color">
		<joint name="${name}_wheel_joint" type="continuous">
			<origin xyz="${xyz}" rpy="${rpy}"/>
			<parent link="${parent}"/>
			<child link="${name}_wheel"/>
			<axis xyz="0 0 ${1*flip}"/>
			<anchor xyz="0 0 0"/>
			<limit effort="100" velocity="100" k_velocity="0"/>
			<joint_properties damping="0.0" friction="0.0"/>
		</joint>

		<link name="${name}_wheel">
			<visual name="${name}_wheel_visual">
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry name="{name}_wheel_geometry">
					<cylinder radius="${radius}" length="${length}"/>
				</geometry>
				<xacro:color_material color="${color}"/>
			</visual>
			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<cylinder radius="${radius}" length="${length}"/>
				</geometry>
			</collision>
			<xacro:cylinder_inertial radius="${radius}" length="${length}" mass="1.0" />
		</link>

		<xacro:color_gazebo parent="${name}_wheel" color="${color}"/>
	</xacro:macro>

	<!-- steering joint -->
	<xacro:macro name="tricycle_steering" params="name parent xyz rpy radius length anglelimit flip=1 color=blue">
		<joint name="${name}_steering_joint" type="continuous">
			<origin xyz="${xyz}" rpy="${rpy}"/>
			<parent link="${parent}"/>
			<child link="${name}_steering"/>
			<axis xyz="0 1 0"/>
			<anchor xyz="0 0 0"/>
			<limit effort="10" velocity="10" lower="${-anglelimit}" upper="${anglelimit}"/>
			<dynamics damping="0.0" friction="0.0"/>
		</joint>

		<link name="${name}_steering">
			<visual name="${name}_visual">
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry name="${name}_geometry">
					<cylinder radius="${radius / 8.0}" length="${length * 2}"/>
				</geometry>
				<xacro:color_material color="${color}"/>
			</visual>
			<xacro:cylinder_inertial radius="${radius / 8.0}" length="${length* 2}" mass="1.0" />
		</link>

		<xacro:color_gazebo parent="${name}_steering" color="${color}"/>
		<xacro:tricycle_wheel name="${name}"  parent="${name}_steering" flip="${flip}"  xyz="0 0 0" rpy="0 0 0" radius="${radius}" length="${length}" color="${color}"/>
	</xacro:macro>

	<!-- wheel joint -->
	<xacro:macro name="tricycle_wheel_actuated" params="name parent xyz rpy radius length color=blue">
		<joint name="${name}_driver_joint" type="continuous">
			<origin xyz="${xyz}" rpy="${rpy}"/>
			<parent link="${parent}"/>
			<child link="${name}_driver"/>
			<axis xyz="0 1 0"/>
			<anchor xyz="0 0 0"/>
			<limit effort="100" velocity="100" k_velocity="0"/>
			<joint_properties damping="0.0" friction="0.0"/>
		</joint>

		<link name="${name}_driver">
			<visual name="${name}_visual">
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry name="${name}_geometry">
					<cylinder radius="${radius / 8.0}" length="${length * 2}"/>
				</geometry>
				<xacro:color_material color="${color}"/>
			</visual>
			<xacro:cylinder_inertial radius="${radius / 8.0}" length="${length* 2}" mass="1.0" />
		</link>

		<xacro:color_gazebo parent="${name}_driver" color="${color}"/>
		<xacro:tricycle_wheel name="${name}"  parent="${name}_driver"  xyz="0 0 0" rpy="0 0 0" radius="${radius}" length="${length}" color="${color}"/>
	</xacro:macro>

	<!-- ====================================================
                           Tricycle Drive
     ========================================================= -->
	<xacro:macro name="tricycle_drive">
		<gazebo>
			<plugin name="tricycle_drive_controller" filename="libgazebo_ros_tricycle_drive.so">
				<rosDebugLevel>Debug</rosDebugLevel>
				<robotNamespace></robotNamespace>
				<publishWheelTF>false</publishWheelTF>
				<publishWheelJointState>true</publishWheelJointState>
				<alwaysOn>true</alwaysOn>
				<steeringJoint>front_steering_joint</steeringJoint>
				<actuatedWheelJoint>left_wheel_joint</actuatedWheelJoint>
				<encoderWheelLeftJoint>left_wheel_joint</encoderWheelLeftJoint>
				<encoderWheelRightJoint>right_wheel_joint</encoderWheelRightJoint>
				<actuatedWheelDiameter>0.135</actuatedWheelDiameter>
				<encoderWheelDiameter>0.135</encoderWheelDiameter>
				<encoderWheelSeparation>0.548</encoderWheelSeparation>
				<commandTopic>cmd_vel</commandTopic>
				<odometryTopic>odom</odometryTopic>
				<odometryFrame>odom</odometryFrame>
				<odometrySource>encoder</odometrySource>
				<robotBaseFrame>base_link</robotBaseFrame>
				<updateRate>10.0</updateRate>
				<wheelAcceleration>1.8</wheelAcceleration>
				<wheelDeceleration>5.0</wheelDeceleration>
				<wheelSpeedTolerance>0.05</wheelSpeedTolerance>
				<wheelTorque>20</wheelTorque>
				<steeringSpeed>0.4</steeringSpeed>
				<steeringAngleTolerance>0.02</steeringAngleTolerance>
			</plugin>
		</gazebo>
	</xacro:macro>


</robot>
